<?php
# This file was automatically generated by the MediaWiki 1.26.2
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

require_once("../application/config/settings.php");

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;
$wgSitename = "HEP-Knowledge Base";
$wgMetaNamespace = "Demo_mediawiki";

define('APPLICATION_NAME', SITE_APPLICATION_NAME);
define('BASE_URL','https://'.$_SERVER['HTTP_HOST']);
$arrURI = explode('/'.APPLICATION_NAME.'/', $_SERVER['REQUEST_URI']);
define('SERVER_NAME', BASE_URL);
define('SCRIPT_PATH', $arrURI[0] . '/'.APPLICATION_NAME.'/knowledgebase');
//define('BASE_URL_CUSTOM', 'http://' . $_SERVER['HTTP_HOST'] . $arrURI[0] . '/hotel_portal/');
define('LOGOUT_URL', BASE_URL . $arrURI[0] . '/'.APPLICATION_NAME.'/users/logout');
define('LOGIN_URL', BASE_URL . $arrURI[0] . '/'.APPLICATION_NAME.'/users/login');

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
//$wgScriptPath = "/team1/hotel_portal/knowledgebase";
$wgScriptPath = SCRIPT_PATH;

require_once("includes/json/FormatJson.php");

## The protocol and server name to use in fully-qualified URLs
//$wgServer = "http://new.anasource.com";
$wgServer = SERVER_NAME;

global $wgBaseLogoutUrl;
//$wgBaseLogoutUrl = "http://new.anasource.com/team1/hotel_portal/users/logout";
$wgBaseLogoutUrl = LOGOUT_URL;

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "$wgResourceBasePath/resources/assets/wiki.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "apache@localhost";
$wgPasswordSender = "apache@localhost";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;
$wgShowExceptionDetails = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = SITE_HOSTNAME;
$wgDBname = SITE_DATABASE;
$wgDBuser = SITE_USERNAME;

$wgDBpassword = 'bayernmunich1';//SITE_PASSWORD;

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "en";

$wgSecretKey = "f655a8d1ea4257da5738d5fd47cbcf3b0d6cdab03b6eef49b48ca3a2f81354e5";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "8645b6a5903170cb";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "Metrolook";
$wgNavBarClasses = 'navbar-inverse';
$wgTOCLocation = 'sidebar';

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'CologneBlue' );
wfLoadSkin( 'Modern' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Vector' );
wfLoadSkin( 'Metrolook' );

# End of automatically generated settings.
# Add more configuration options below.
$wgGroupPermissions['*']['read'] = false;

$wgGroupPermissions['Trustworthy'] = $wgGroupPermissions['user'];
$wgGroupPermissions['Noteditable'] = $wgGroupPermissions['user'];
//$wgGroupPermissions['Trustworthy']['patrol'] = false;
//$wgGroupPermissions['Trustworthy']['delete'] = false;

$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['user']['edit'] = false;
$wgGroupPermissions['sysop']['edit'] = true;
$wgGroupPermissions['Noteditable']['edit'] = false;

require_once "$IP/extensions/Moderation/Moderation.php";

require_once( "$IP/skins/bootstrap-mediawiki/bootstrap-mediawiki.php" );

require_once "$IP/extensions/Comments/Comments.php";

require_once "$IP/extensions/CategoryTree/CategoryTree.php";
$wgUseAjax = true;

unset( $wgFooterIcons['poweredby'] );
wfLoadExtension( 'MsUpload' ); 

$wgEnableUploads = true;
//For Editor
require_once("$IP/extensions/TinyMCE_MW/TinyMCE_MW.php");  //Extension php file location
$wgUseTinymce = true;       //Init needed for clicking on a new article link
$wgDefaultUserOptions ['showtoolbar'] = 0;     //Disable the standard wiki edit toolbar without editing your DefaultSettings.php file
$wgTinymceTheme = "msword";                   //Options are "simple", "advanced", "msword"
$wgMyWikiURL = "$wgServer/$wgScriptPath/";   //Configuration setting for link URLs
$wgExt_valid_elements = "data[table|template],repeat[table|sort],categorytree[mode|depth],inputbox[type|bgcolor|width|default|preload|editintro|buttonlabel|searchbuttonlabel|break],big,img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name]";       
//Global variable for valid MediaWiki Elements to be passed to the TinyMCE_MW.php file

$wgAllowExternalImages = true;

/*
require_once "$IP/extensions/WikiEditor/WikiEditor.php";

# Enables use of WikiEditor by default but still allows users to disable it in preferences
$wgDefaultUserOptions['usebetatoolbar'] = 1;

# Enables link and table wizards by default but still allows users to disable them in preferences
$wgDefaultUserOptions['usebetatoolbar-cgd'] = 1;

# Displays the Preview and Changes tabs
$wgDefaultUserOptions['wikieditor-preview'] = 1;

# Displays the Publish and Cancel buttons on the top right side
$wgDefaultUserOptions['wikieditor-publish'] = 1;
*/
//Editor end

$wgMetrolookDownArrow = false;
$wgMetrolookBartile = false;
$wgMetrolookUploadButton = false;
$wgMetrolookMobile = true;
$wgMetrolookDisableAvatar = false;
$wgGroupPermissions['*']['createaccount'] = true;

$wgHooks['SkinTemplateOutputPageBeforeExec'][] = 'lfChangeMainPageURL';
function lfChangeMainPageURL( $sk, &$tpl ) {  
        $arrURI = explode('/'.APPLICATION_NAME.'/', $_SERVER['REQUEST_URI']);
	$tpl->data['nav_urls']['mainpage']['href'] = BASE_URL . $arrURI[0] . '/'.APPLICATION_NAME; // Point the main page url to an absolute url
 return true;
}
//Check if User is logged In
function checkUserLoggedIn() {
    global $wgUser;
    if( !$wgUser->isLoggedIn() ) {
        header('Location: '.LOGIN_URL);
    }
    return true;
}
$wgHooks['BeforePageDisplay'][] = 'checkUserLoggedIn';
$wgDefaultUserOptions['watchdefault'] = 0;
$wgFavicon = $wgScriptPath."/images/favicon.ico";

/*
$wgCookieExpiration = 0;
session_start();

$now = time();

if(isset($_SESSION['time']))
{  
 if($now - $_SESSION['time'] >= 1800)
 {
  session_destroy();
  header('Location: '.$wgBaseLogoutUrl);
 }else{
  $_SESSION['time'] = $now;
 }
}*/